#!/usr/bin/env python
# coding=utf-8

__author__ = 'dunkebiao'

"install pssh file."

import os
import sys
import getopt

try:
    import urllib2
except ImportError:
    import urllib.request as urllib2


class Install:
    install_dir = ''
    filename = ''
    pssh = ''

    def __init__(self, install_dir, filename):
        self.install_dir = install_dir
        self.filename = filename

    def get_pssh(self):
        """
            get pssh file
        :return:obj
        """
        try:
            self.pssh = urllib2.urlopen('https://raw.githubusercontent.com/dunkebiao/pssh/master/ssh.py').read()
        except urllib2.HTTPError as e:
            sys.exit(e.code)
        except urllib2.URLError as e:
            sys.exit(e.reason)
        return self

    def put_pssh(self):
        """
            write pssh file
        :return:obj
        """
        try:
            f = open(self.install_dir + '/' + self.filename, 'w+')
            f.writelines(self.pssh)
            f.close()
        except IOError as e:
            sys.exit(e)
        try:
            os.system('chmod +x ' + self.install_dir + '/' + self.filename)
        except:
            sys.exit('[Error] install failure')
        return self

    def do(self):
        self.get_pssh()
        self.put_pssh()


def main():
    """
        this is mian
    """
    try:
        options, args = getopt.getopt(sys.argv[1:], "f:d:", ["filename=", "install-dir="])
    except getopt.GetoptError as e:
        sys.exit(e.msg)

    install_dir = '/usr/local/bin'
    filename = 'pssh'

    for name, value in options:
        if name in ("-d", "--install-dir"):
            if value:
                install_dir = value.rsplit('/')
        if name in ("-f", "--filename"):
            if value:
                filename = value

    Install(install_dir, filename).do()
    print('ok')


if __name__ == '__main__':
    main()
