#!/usr/bin/env python
# coding=utf-8

__author__ = 'dunkebiao'

"install pssh file."

import os
import sys
import getopt
import platform


def download(install_dir, filename, version):
    sysname = "-".join([platform.uname()[0], platform.uname()[4]])
    url = 'https://github.com/dunkebiao/pssh/releases/download/' + version + '/' + sysname + '-pssh'
    file_path = install_dir + '/' + filename
    try:
        os.system('curl -L -o %s %s' % (file_path, url))
        os.system('chmod +x ' + file_path)
    except:
        sys.exit('[Error] install failure')


def main():
    """
        this is mian
    """
    try:
        options, args = getopt.getopt(sys.argv[1:], "f:d:", ["filename=", "install-dir="])
    except getopt.GetoptError as e:
        sys.exit(e.msg)

    install_dir = '/usr/local/bin'
    filename = 'pssh'
    version = 'v3.0'

    for name, value in options:
        if name in ("-d", "--install-dir"):
            if value:
                install_dir = value.rstrip('/')
        if name in ("-f", "--filename"):
            if value:
                filename = value

    download(install_dir, filename, version)
    print('ok')


if __name__ == '__main__':
    main()
